[package]
name = "fake_github"
version = "0.1.0"
authors = ["Renato Zannon <renato@rrsz.com.br>"]

[dependencies]
futures = "0.1"
gotham = "0.2"
hyper = "0.11"
ipc-channel = "0.10"
mime = "0.3"
serde = "1"
serde_derive = "1"
